// This file was generated by iSukces.Templates ver 1.26.104.9
// Get the latest version from https://raw.githubusercontent.com/isukces/iSukces.Templates/main/Code/iSukces.Templates/PrimitiveObsession.ttinclude

namespace iSukces.Cli.Whisper;

public readonly struct WhisperModelName: IComparable, IComparable<string>, IComparable<WhisperModelName>, IEquatable<string>, IEquatable<WhisperModelName>
{
    public WhisperModelName(string? value) => _value = value?.Trim();

    public override bool Equals(object? obj) => obj is WhisperModelName x && Equals(x);

    public bool Equals(WhisperModelName other) => Comparer.Equals(Value, other.Value);

    public override int GetHashCode() => Comparer.GetHashCode(Value);

    public bool Equals(string? other) => Comparer.Equals(Value, other ?? string.Empty);

    public int CompareTo(WhisperModelName other) => Comparer.Compare(Value, other.Value);

    public int CompareTo(object? obj)
    {
        if (obj is null) return 1;
        return obj is WhisperModelName other
            ? CompareTo(other)
            : throw new ArgumentException($"Object must be of type {nameof(WhisperModelName)}");
    }

    public int CompareTo(string? other) => Comparer.Compare(Value, other ?? string.Empty);

    public static bool operator ==(WhisperModelName left, WhisperModelName right) => left.Equals(right);

    public static bool operator !=(WhisperModelName left, WhisperModelName right) => !left.Equals(right);

    private readonly string? _value;

    public string Value => _value ?? string.Empty;

    public static WhisperModelName Empty { get; } = new WhisperModelName(null);

    public bool IsEmpty => string.IsNullOrEmpty(_value);

    public static StringComparer Comparer => StringComparer.Ordinal;

}



